
package dashboard;

import config.connectDB;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class adminDash extends javax.swing.JFrame {

    private Color[] originalPanelColors = new Color[7];
    private Color hoverPanelColor = Color.WHITE; // White hover color
    private JPanel[] panels = new JPanel[7];
    private JLabel[] labels = new JLabel[7];
    private Color[] originalLabelColors = new Color[7];
    private Color hoverLabelColor = new Color(0, 204, 204);
    
    public adminDash() {
        initComponents();
        loadUsers();
        
        panels[0] = dashpanel; 
        labels[0] = home;
        panels[1] = dashpanel1; 
        labels[1] = dashboard;
        panels[2] = dashpanel2; 
        labels[2] = patients; 
        panels[3] = dashpanel3; 
        labels[3] = doctors; 
        panels[4] = dashpanel4; 
        labels[4] = staffs; 
        panels[5] = dashpanel5; 
        labels[5] = appointments; 
        panels[6] = dashpanel6; 
        labels[6] = payment; 

        for (int i = 0; i < 7; i++) {
        originalPanelColors[i] = panels[i].getBackground();
        originalLabelColors[i] = labels[i].getForeground();
        hoverPanelListener listener = new hoverPanelListener(
            hoverPanelColor, 
            originalPanelColors[i], 
            labels[i], 
            hoverLabelColor 
        );
        panels[i].addMouseListener(listener);

        panels[i].setOpaque(true); 
        panels[i].repaint();

        labels[i].repaint(); 
        }
        

    }
    
        
    private void loadUsers() {
         
         connectDB connect = new connectDB();
         
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("User ID");
        model.addColumn("First Name");
        model.addColumn("Middle Name");
        model.addColumn("Last Name");
        model.addColumn("Contact Number");
        model.addColumn("Email");
        model.addColumn("Type");
        model.addColumn("Username");
        model.addColumn("Status");
        
           
        try {
            Connection conn = connect.getConnection(); // Get database connection
            if (conn == null) {
                System.out.println("Database connection failed!");
                return;
            }

            String query = "SELECT user_id, user_fname, user_middle, user_lname, contact, email, user_type, user_name, status FROM users";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("user_id"),
                    rs.getString("user_fname"),
                    rs.getString("user_middle"),
                    rs.getString("user_lname"),
                    rs.getString("contact"),
                    rs.getString("email"),
                    rs.getString("user_type"),
                    rs.getString("user_name"),
                    rs.getString("status"),
                   
                });
            }

            dashTable.setModel(model);
            model.fireTableDataChanged(); 

            rs.close();
            stmt.close();
            conn.close(); 
             
       
        } catch (SQLException ex) {
            System.out.println("Error loading users: " + ex.getMessage());
            ex.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dashTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        signInUser1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        adminmsg = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        payment = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        patients = new javax.swing.JLabel();
        doctors = new javax.swing.JLabel();
        staffs = new javax.swing.JLabel();
        appointments = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        OK = new javax.swing.JLabel();
        ADD = new javax.swing.JLabel();
        UPDATE = new javax.swing.JLabel();
        ARCHIVE = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        dashpanel1 = new javax.swing.JPanel();
        dashpanel2 = new javax.swing.JPanel();
        dashpanel3 = new javax.swing.JPanel();
        dashpanel4 = new javax.swing.JPanel();
        dashpanel5 = new javax.swing.JPanel();
        dashpanel6 = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        jInternalFrame2.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashTable.setBackground(new java.awt.Color(0, 0, 0));
        dashTable.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        dashTable.setForeground(new java.awt.Color(204, 255, 255));
        dashTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dashTable.setEnabled(false);
        jScrollPane1.setViewportView(dashTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 610, 380));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medlogo1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        signInUser1.setBackground(new java.awt.Color(255, 255, 255));
        signInUser1.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signInUser1.setForeground(new java.awt.Color(0, 204, 204));
        signInUser1.setText("Care Connect");
        jPanel2.add(signInUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Super Admin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 110, 30));

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 100));

        welcome.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("DentaLink");
        jPanel2.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        adminmsg.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        adminmsg.setForeground(new java.awt.Color(255, 255, 255));
        adminmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminmsg.setText("Welcome,");
        jPanel2.add(adminmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        LOGOUT.setBackground(new java.awt.Color(255, 255, 255));
        LOGOUT.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(0, 204, 204));
        LOGOUT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGOUT.setText("LOG OUT");
        LOGOUT.setDoubleBuffered(true);
        LOGOUT.setOpaque(true);
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
        });
        jPanel2.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 130, 30));

        payment.setBackground(new java.awt.Color(255, 255, 255));
        payment.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        payment.setForeground(new java.awt.Color(255, 255, 255));
        payment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payment.setText("Payment");
        jPanel2.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 220, 30));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 30));

        dashboard.setBackground(new java.awt.Color(255, 255, 255));
        dashboard.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("Dashboard");
        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 30));

        patients.setBackground(new java.awt.Color(255, 255, 255));
        patients.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        patients.setForeground(new java.awt.Color(255, 255, 255));
        patients.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patients.setText("Manage Patients");
        jPanel2.add(patients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 30));

        doctors.setBackground(new java.awt.Color(255, 255, 255));
        doctors.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        doctors.setForeground(new java.awt.Color(255, 255, 255));
        doctors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctors.setText("Manage Doctors");
        jPanel2.add(doctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 30));

        staffs.setBackground(new java.awt.Color(255, 255, 255));
        staffs.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        staffs.setForeground(new java.awt.Color(255, 255, 255));
        staffs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffs.setText("Manage Staffs");
        jPanel2.add(staffs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 30));

        appointments.setBackground(new java.awt.Color(255, 255, 255));
        appointments.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        appointments.setForeground(new java.awt.Color(255, 255, 255));
        appointments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointments.setText("Appointments");
        jPanel2.add(appointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 220, 30));

        dashpanel.setBackground(new java.awt.Color(0, 204, 204));
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 590));

        OK.setBackground(new java.awt.Color(0, 204, 204));
        OK.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        OK.setForeground(new java.awt.Color(255, 255, 255));
        OK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OK.setText("OK");
        OK.setDoubleBuffered(true);
        OK.setOpaque(true);
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKMouseClicked(evt);
            }
        });
        jPanel1.add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 50, 30));

        ADD.setBackground(new java.awt.Color(0, 204, 204));
        ADD.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADD.setText("Add");
        ADD.setDoubleBuffered(true);
        ADD.setOpaque(true);
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 30));

        UPDATE.setBackground(new java.awt.Color(0, 204, 204));
        UPDATE.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE.setText("Update");
        UPDATE.setDoubleBuffered(true);
        UPDATE.setOpaque(true);
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 130, 30));

        ARCHIVE.setBackground(new java.awt.Color(0, 204, 204));
        ARCHIVE.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        ARCHIVE.setForeground(new java.awt.Color(255, 255, 255));
        ARCHIVE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ARCHIVE.setText("Archive");
        ARCHIVE.setDoubleBuffered(true);
        ARCHIVE.setOpaque(true);
        ARCHIVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ARCHIVEMouseClicked(evt);
            }
        });
        jPanel1.add(ARCHIVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 130, 30));

        BACK.setBackground(new java.awt.Color(0, 204, 204));
        BACK.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        BACK.setForeground(new java.awt.Color(255, 255, 255));
        BACK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BACK.setText("Back");
        BACK.setDoubleBuffered(true);
        BACK.setOpaque(true);
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 130, 30));

        dashpanel1.setBackground(new java.awt.Color(0, 204, 204));
        dashpanel1.setInheritsPopupMenu(true);
        dashpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(dashpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 30));

        dashpanel2.setBackground(new java.awt.Color(0, 204, 204));
        dashpanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        dashpanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(dashpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 220, 30));

        dashpanel3.setBackground(new java.awt.Color(0, 204, 204));
        dashpanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(dashpanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 220, 30));

        dashpanel4.setBackground(new java.awt.Color(0, 204, 204));
        dashpanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(dashpanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 220, 30));

        dashpanel5.setBackground(new java.awt.Color(0, 204, 204));
        dashpanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(dashpanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 220, 30));

        dashpanel6.setBackground(new java.awt.Color(0, 204, 204));
        dashpanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(dashpanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        this.dispose();
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseClicked


        //        dashboard dash = new dashboard();
        //        dash.setLocationRelativeTo(null);
        //        dash.setVisible(true);
        //
        //        this.dispose();
    }//GEN-LAST:event_OKMouseClicked

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseClicked

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseClicked

    private void ARCHIVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ARCHIVEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ARCHIVEMouseClicked

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD;
    private javax.swing.JLabel ARCHIVE;
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel OK;
    private javax.swing.JLabel UPDATE;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel adminmsg;
    private javax.swing.JLabel appointments;
    private javax.swing.JTable dashTable;
    private javax.swing.JLabel dashboard;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JPanel dashpanel1;
    private javax.swing.JPanel dashpanel2;
    private javax.swing.JPanel dashpanel3;
    private javax.swing.JPanel dashpanel4;
    private javax.swing.JPanel dashpanel5;
    private javax.swing.JPanel dashpanel6;
    private javax.swing.JLabel doctors;
    private javax.swing.JLabel home;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patients;
    private javax.swing.JLabel payment;
    private javax.swing.JLabel signInUser1;
    private javax.swing.JLabel staffs;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

}