
package dashboard;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import signInUp.signIn;

public class doctorDash extends javax.swing.JFrame {

    private int loggedInDoctorId;
    
    public doctorDash(int userId) {
        initComponents();
        this.loggedInDoctorId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        signInUser1 = new javax.swing.JLabel();
        doctor = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        adminmsg = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ADD = new javax.swing.JLabel();
        UPDATE = new javax.swing.JLabel();
        ARCHIVE = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        OK = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medlogo1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        signInUser1.setBackground(new java.awt.Color(255, 255, 255));
        signInUser1.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        signInUser1.setForeground(new java.awt.Color(0, 204, 204));
        signInUser1.setText("Care Connect");
        jPanel2.add(signInUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, 20));

        doctor.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        doctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 100, 30));

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor.png"))); // NOI18N
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 100));

        welcome.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Care Connect");
        jPanel2.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        adminmsg.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        adminmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminmsg.setText("Welcome,");
        jPanel2.add(adminmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        LOGOUT.setBackground(new java.awt.Color(255, 255, 255));
        LOGOUT.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(0, 204, 204));
        LOGOUT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGOUT.setText("LOG OUT");
        LOGOUT.setDoubleBuffered(true);
        LOGOUT.setOpaque(true);
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
        });
        jPanel2.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 660));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 820, 460));

        ADD.setBackground(new java.awt.Color(0, 204, 204));
        ADD.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADD.setText("Add");
        ADD.setDoubleBuffered(true);
        ADD.setOpaque(true);
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 130, 30));

        UPDATE.setBackground(new java.awt.Color(0, 204, 204));
        UPDATE.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE.setText("Update");
        UPDATE.setDoubleBuffered(true);
        UPDATE.setOpaque(true);
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 130, 30));

        ARCHIVE.setBackground(new java.awt.Color(0, 204, 204));
        ARCHIVE.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        ARCHIVE.setForeground(new java.awt.Color(255, 255, 255));
        ARCHIVE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ARCHIVE.setText("Archive");
        ARCHIVE.setDoubleBuffered(true);
        ARCHIVE.setOpaque(true);
        ARCHIVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ARCHIVEMouseClicked(evt);
            }
        });
        jPanel1.add(ARCHIVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 130, 30));

        BACK.setBackground(new java.awt.Color(0, 204, 204));
        BACK.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        BACK.setForeground(new java.awt.Color(255, 255, 255));
        BACK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BACK.setText("Back");
        BACK.setDoubleBuffered(true);
        BACK.setOpaque(true);
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 130, 30));

        OK.setBackground(new java.awt.Color(0, 204, 204));
        OK.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        OK.setForeground(new java.awt.Color(255, 255, 255));
        OK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OK.setText("OK");
        OK.setDoubleBuffered(true);
        OK.setOpaque(true);
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKMouseClicked(evt);
            }
        });
        jPanel1.add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 50, 30));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        jPanel3.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctor Dashboard");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 840, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        
        int choice = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out?", 
        "Confirm Logout", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        new ImageIcon(getClass().getResource("/images/logoutIcon.png")) 
        );

        if (choice == JOptionPane.YES_OPTION) {
            signIn sn = new signIn();
            sn.setLocationRelativeTo(null);
            sn.setVisible(true);

            this.dispose();
        }
      
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseClicked

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseClicked

    private void ARCHIVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ARCHIVEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ARCHIVEMouseClicked

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKMouseClicked

    private void OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseClicked

        //        dashboard dash = new dashboard();
        //        dash.setLocationRelativeTo(null);
        //        dash.setVisible(true);
        //
        //        this.dispose();
    }//GEN-LAST:event_OKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorDash(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD;
    private javax.swing.JLabel ARCHIVE;
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel OK;
    private javax.swing.JLabel UPDATE;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel adminmsg;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel signInUser1;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
